name: Terraform CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  TF_IN_AUTOMATION: "true"
  YC_CLOUD_ID: "b1gvjpk4qbrvling8qq1"
  YC_FOLDER_ID: "b1gse67sen06i8u6ri78"
  YC_TOKEN: ${{ secrets.YC_TOKEN }}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    # тут настраиваем доступ к Object Storage (S3 backend)
    env:
      AWS_ACCESS_KEY_ID:     ${{ secrets.YC_OBJ_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_OBJ_SECRET_KEY }}
      AWS_DEFAULT_REGION:    "ru-central1"
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: infra
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -input=false

      - name: Terraform Apply (only on main)
        if: github.ref == 'refs/heads/main'
        working-directory: infra
        run: terraform apply -auto-approve -input=false
